"""Compose the solved transform into the URDF mount frame and persist it.

Solver outputs T_eef_color (link_eef -> xarm_camera_color_optical_frame). The URDF
attaches xarm_camera_link to link_eef; color_optical is a fixed child of camera_link.
So the URDF mount-joint origin we must write is:
    T_eef_mount = T_eef_color @ inv(T_mount_color)
where T_mount_color is the (factory, unchanged) camera_link->color_optical chain.
"""
import re
import time
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation as R
from handeye_calib import transforms as tf


def compose_eef_to_mount(T_eef_color, T_mount_color):
    return np.asarray(T_eef_color) @ tf.invert(T_mount_color)


def _xyz_rpy(T):
    xyz = np.asarray(T)[:3, 3]
    rpy = R.from_matrix(np.asarray(T)[:3, :3]).as_euler('xyz')
    return " ".join(f"{v:.9g}" for v in xyz), " ".join(f"{v:.9g}" for v in rpy)


def handeye_yaml_dict(T_eef_mount, T_eef_color, num_poses, metrics, date,
                      square_len_m=0.04):
    mount_xyz, mount_rpy = _xyz_rpy(T_eef_mount)
    color_xyz, color_rpy = _xyz_rpy(T_eef_color)
    return {"hand_eye": {
        "reference_frame": "link_eef",
        "camera_frame": "xarm_camera_link",
        "arm_to_camera_xyz": mount_xyz,
        "arm_to_camera_rpy": mount_rpy,
        "color_optical_xyz": color_xyz,
        "color_optical_rpy": color_rpy,
        "calibration_date": date,
        "calibration_method": "calibrateHandEye+BA",
        "board": {"type": "charuco", "squares": "5x5", "square_len_m": square_len_m},
        "num_poses": int(num_poses),
        # Residual over ALL samples used in the fit (no train/held-out split);
        # an independently-recorded validation set measures generalization.
        "residual_trans_rmse_m": round(float(metrics["trans_rmse_m"]), 6),
        "residual_rot_rmse_rad": round(float(metrics["rot_rmse_rad"]), 6),
        "residual_reproj_px": round(float(metrics["reproj_px"]), 4),
    }}


def patch_urdf_origin(xacro_text, joint_name, xyz, rpy):
    """Replace the <origin .../> inside the named <joint>, leaving everything else intact."""
    xyz_s = " ".join(str(v) for v in xyz)
    rpy_s = " ".join(str(v) for v in rpy)
    pat = re.compile(
        r'(<joint\s+name="' + re.escape(joint_name) + r'".*?<origin\b)[^>]*?(/?>)',
        re.DOTALL)
    if not pat.search(xacro_text):
        raise ValueError(f"origin for joint {joint_name} not found")
    return pat.sub(rf'\1 xyz="{xyz_s}" rpy="{rpy_s}"\2', xacro_text, count=1)


def resolve_robot_xacro_path(robot_name, basic_repo_root):
    """Resolve the per-robot wrist-camera xacro override path.

    Returns ``<basic_repo_root>/src/tinker_robot_config/robots/<robot_name>/wrist_camera.xacro``
    when ``robot_name`` is truthy, else ``None``. Does NOT check existence —
    the caller decides whether to seed (file absent) or patch (file present).

    The path convention mirrors the existing per-robot config layout (see
    ``src/tk25_basic/src/tinker_robot_config/robots/tinker1/`` etc.); the
    handeye_web Promote tab uses it so calibrating tinker1 doesn't
    overwrite tinker2's mount (and vice versa).
    """
    if not robot_name:
        return None
    return (Path(basic_repo_root) / "src" / "tinker_robot_config"
            / "robots" / robot_name / "wrist_camera.xacro")


_OVERRIDE_TEMPLATE = """<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="handeye_override_{robot}">
  <!-- Generated by handeye_web Promote ({stamp}).
       Auto-included by xarm_description/urdf/camera/realsense_d435i.urdf.xacro
       when ROBOT_NAME={robot}. Redefines handeye_xyz/handeye_rpy
       (link_eef -> xarm_camera_link) with the calibrated values from
       hand_eye.yaml arm_to_camera_xyz/rpy. Prior versions are backed up
       alongside as wrist_camera.xacro.old-<ts>. -->
  <xacro:property name="handeye_xyz" value="{xyz_str}"/>
  <xacro:property name="handeye_rpy" value="{rpy_str}"/>
</robot>
"""


def seed_handeye_override_xacro(robot_name, xyz_str, rpy_str):
    """Build the per-robot wrist_camera.xacro override body (property form —
    the ONLY form the vendor include consumes; the pre-2026-07-03 <joint>
    form silently never took effect)."""
    return _OVERRIDE_TEMPLATE.format(
        robot=robot_name, xyz_str=xyz_str, rpy_str=rpy_str,
        stamp=time.strftime('%Y-%m-%dT%H:%M:%S'))


def write_with_backup(path, text):
    """Atomically write ``text`` to ``path``, renaming any existing file aside.

    Existing files are moved to ``<path>.old-<UTC-ish timestamp>`` so the
    operator can recover from a bad promote. The new content is staged in a
    sibling ``<path>.tmp`` first, then ``os.replace``'d into place — so a
    crash mid-write never leaves a half-written target. Returns the backup
    path (str) or ``None`` if no prior file existed; callers use this to
    surface the rollback path in the UI's status line.

    NB: parent directory is created on demand so the per-robot xacro override
    path lands cleanly even when only the robots dir exists.
    """
    import os
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    backup = None
    if os.path.exists(path):
        backup = f"{path}.old-{time.strftime('%Y%m%dT%H%M%S')}"
        os.replace(path, backup)
    tmp = f"{path}.tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)
    return backup


def main():
    raise SystemExit("apply_handeye is used as a library by handeye_web; see README.")
