# Goal: Request to spot objects on shelf
geometry_msgs/PoseStamped shelf_left # in map frame
geometry_msgs/PoseStamped shelf_right # in map frame
float32[] shelf_heights # in meters
string[] item_ids

---
# Result: Categorization results
int32 status
string error_msg
float32[] item_height_grids
int32[] item_horizontal_grids

---
# Feedback: Progress updates
int32 status
string message
