float32 threshold_meters
string target_frame
int32 min_waving_persons
---
int32 status
string error_msg
geometry_msgs/PointStamped[] waving_persons

sensor_msgs/Image rgb_image
sensor_msgs/Image depth_image
sensor_msgs/Image[] segments